### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by cnole** [lsm/micromono#20]
I got an error wenn running the example app:

Error: Cannot find module '/Users/zhengluo/Works/Microservices/micromono/example/server/server.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

Looks like there is no server/ directory in example/, is there other ways to try micromono?

**Comment by lsm** [comment]
The Readme is dated. Try following commands in `example` folder:

`make install`
then
`make cluster`
